language: objective-c
os: osx
xcode_project: Example/Aopubs.xcodeproj
xcode_scheme: Aopubs
before_install:
- brew update
- gem install fir-cli
before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/patient_adolescent_spin_distribute.mobileprovision.enc
  -d -a -out scripts/profile/patient_adolescent_spin_distribute.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/ios_development.cer.enc
  -d -a -out scripts/certs/ios_development.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/certs.p12.enc -d -a
  -out scripts/certs/certs.p12
- ./scripts/add-key.sh
script:
- xctool -project Example/Aopubs.xcodeproj -scheme $APP_NAME -sdk iphoneos  -configuration
  Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="$DEVELOPER_NAME"
after_success:
- ./scripts/sign-and-upload.sh
after_script:
- ./scripts/remove-key.sh
env:
  global:
  - APP_NAME="Aopubs"
  - 'DEVELOPER_NAME="iPhone Distribution: {Zhiwei Lin} ({PE53UGCLR6})"'
  - PROFILE_NAME="patient_adolescent_spin_distribute"
  - secure: oS/2Pwr8JICb0Bjuqv2lzPdF3tZnH4axxQmOEaWrHD/dSHHD4pFPx2lLfJIbSy39KCiPEVZ/5RZ+2j9qVYksa8Sq0ap8DOch72qZvWgiN14dkP1WW9m57+TfJzBYR5TDjS7MOErGPRImylI/brtgHwP+AEg1NKisuoTclDx2xj9afF6cKRaJoANyKSSNxw3wPkhh1qDGHWahDjrIKbR5RFEts7Uqpyi/nTbvUcasFFLQVOdD8+//gPSUBrRA//DphbHB0brFivX/RyTMrVeJPcY2NBdZP9Z6qG8Vd/EKcRxK70fLGtiY/CyAIa5OBgKTFI/4BcVBOpdGUKa2AYNJ2UOpHqWuFPAENGEdOQY6vNuhI2f+2BoI0wvq/kh2E/TWfwG7w/0Ix0B4QMbypt7Sa+wXBd6MgbIOnckQ/rRtiz7S+tM8v5ytrE2/W6aiDsU3r+GS/2Lna08jZ+HM9MNgt1zcSrWKy1hJ0sW8yzUmS1uqNQvZBXS4sD0QSTb/BP0mtZBb8VBdjgpipGVHxtiOgR8cYnwqVDYu7BQHRKeSbCGEMNWnMF70i+Y32zg+sOfLOzltwbAeAGo4M0J3tkl3M3PeGwpJ7JeZ8sgWT/kgrb9zG5r82wu6oO+c8N5g/8ueCyt16AyypHjONC1npGMn0tGrUY61XjZ6aU3jRrdnwt0=
  - secure: wC9FLJP6sTdTvktiBLP2zcTKkrBHAF6hIEj8FA9+lo/0LO2Aw8hueLPFXQJ8/dXp4+1eXcuksl+3k45PtvyLA4o/7N0e+GG24OA2jhj+NbjJRr/QQbeiaO7WvptjAWWUBLadf+XeYNKXTfVLBFI89+hcQb7VY7m907/jozNEV7tWPnVp02/Zr5usEW3GwQDfCcArMccNRTBpCQRg8Exyl4mKdwm2+TxxRyGubSGXtOJCW70+WnDRC2HKc32jfjDbyz45PLMfR/cl8dZdgEo0tPrUY/uqUSAJCB1Va7w2nyGtWOyL8xZKkpcu+k1gT8g1RrxaZqkZa/HPbAAbGuQ3e/7StZYDmzjRoLxtVuD6YJyd/mSIMz4N8psPuSyKFAS3SzZ4FKCNKprnoNCWYuWByk7cu20GH1T9W1N60OIyk3micpFqY8oZxbA1RMhLZri8jra8KbUbMNDoGnxyl2icNCym+lGj0onOAaUX7Gj0evHgNl5L0Dn87tLwEeALJ0/iIdJ5X+vcaV0uLtIfFV7vJXX+UTvtkw3a14qUdyEhgmeMeisP2o1cJHsjjCXKws/Xe3hYj/LbCjydZiDqrbVzXGhezcbHNZZBtUbvvflIew1SxpLsifJn8HjGIfMlMKy585IZ+mt5M0UGH6UV1T5e6HVv8QubXf2aaezout6bG2I=
  - secure: qx2L1zGOWIZT0Z/SxMD6PTzb6BUycUgsdx/XHisDUSWeazIxzAg8TVeZPZYXR/AGRp2W7y3+yJfNIJXyUvAw5LGa/K2FcpoQG0uSOgXRKjiArvjS9382XSACaw58bBB3YksogkuiDG+qJTUBCcEJ0GkwbmdrYnExSTO+VkRpLu8myzoku7ZoLUH0XBSoqm8JEmqgGeoyhTYIudPC4j8JMqYlNKYbFaq1SaWeaRxq0+orqsjENT4/ufj74UtlCkznuEyffmh/ixZTMNwUCS13m3iPSjJdLI7jAIOsbc+knwF4OkXLtW9Ytff7CJqLEChJLS7xMvQUh/AvdqTuvFEzgzHexnYC0WOk8P2hnVsxh2ALprnTGQQEXvJ4CIeqD2WORgM9wXLOS3Zxmq/AzdyS2GkmN/ssWIBV3CbgEWsNlac/CjLWBagEoRPEAqcuaz7CdkYebVTq5674/3tlwcrYLRGcP+hkI65918JNgN6z5D4oTQmXYQeUWWkfNhf6uIExPLCbHdM0K+DfeTFfpWqZ0de2ike6EKqz0CI+0OQ4ZktsJf/pwDuLgm0WMHqkZYfcBGPlqt1aKAq81j26HTDmq26elC4fYd7hOshCqb5NT9eQvaxwFkBFC3O1zGyGjJ0UI3kwIRRZBQcS7dx8vfiBIr07qOISmSW38ze3e+pG0fU=
